spring:
  application:
    name: payment-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/spring2
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8090
